### ISSUE TITLE
Passthrough arguments into constructor

### ISSUE THREAD

**Issue by KES777** [avkhozov/Mojolicious-Plugin-Model#8]
Follow Mojolicious spirit and passthrough arguments, e.g.:

    $self->model( 'File',  'Avatar',  storage => 'Local' );

The `new` sub of `App::Model::File::new` should be called with `Avatar`, `storage => 'Local'` arguments too:

    Mojolicious/Plugin/Model.pm
    -18:       my ($self, $name) = @_;
    +18:       my ($self, $name) = (shift,shift);

    -35:         $model = $class->new(ref $params eq 'HASH' ? %$params : (), app => $app);
    +35:         $model = $class->new(ref $params eq 'HASH' ? %$params : (), app => $app, @_);

**Comment by avkhozov** [comment]
Thanks, added.

**Comment by KES777** [comment]
Sorry, this was bad idea. I did not know that `Model` is singleton. Passing arguments to constructor will cause unexpected results see [this](https://github.com/avkhozov/Mojolicious-Plugin-Model/issues/9#issuecomment-287460234)

**Comment by avkhozov** [comment]
Yes, I agree. I incorrectly thought it was like to the option `params` for model. I will rollback release, sorry.

**Comment by KES777** [comment]
No problem. All is OK
