### ISSUE TITLE
Feature request: Pass controller object as argument to model contructor

### ISSUE THREAD

**Issue by KES777** [avkhozov/Mojolicious-Plugin-Model#9]
-$model = $class->new(ref $params eq 'HASH' ? %$params : (), app => $app);
    +$model = $class->new(ref $params eq 'HASH' ? %$params : (), app => $app, c => $self);

This allows to do things based on current request. 

For example we may limit access only to owned data currently in session:

    # in controller
    $self->model( 'file' );

    # in model:
    package App::Model::File;
    sub new { 
         my( ... %args ) =  @_;
         make_obj( 'SELECT * FROM files WHERE user_id = ?', $args->{ c }->current_user_id );
         ...
    }

**Comment by KES777** [comment]
We should not do this. Because this will conflict with caching mechanizm:

    24: return $model if $model = $plugin->{models}{$name}

Arguments will be just ignored for second call, because we already have `Model` of this type created.

    $self->model( 'File', a => 1 );
    $self->model( 'File', b => 2 ); # The first model with { a => 1 } is returned

**Comment by KES777** [comment]
I think we may check `@_` if it do not exists, then we may create plugin or return it from cache, But when `@_` supplied we should bypass cache and create new plugin with given arguments.

What you would say?

**Comment by avkhozov** [comment]
`Model` in this plugin is a singleton object. It's just a set of related methods, which can be called from controllers/templates and always has an `app` attribute for easy access to config/log/renderer/...

But with this plugin you can create a new model object from methods. So you can create as many instances of model as you need. See example in tests https://github.com/avkhozov/Mojolicious-Plugin-Model/blob/master/t/lite.t#L26-L33
